// packages/react-sample/src/pages/Callback/index.tsx
import { useHandleSignInCallback } from '@logto/react';
import React from 'react';
import { useNavigate } from 'react-router-dom';

const Callback = () => {
  const navigate = useNavigate();
  const { isLoading } = useHandleSignInCallback(() => {
    navigate('/');
  });

  return isLoading ? <p>Redirecting...</p> : null;
};

export default Callback;

// packages/solid-sample/src/pages/Callback.tsx
import { useHandleSignInCallback } from '@logto/solid';
import { useNavigate } from '@solidjs/router';
import { Show } from 'solid-js';

export default function Callback() {
  const navigate = useNavigate();
  const { isLoading } = useHandleSignInCallback(() => {
    console.log("???")
    navigate('/');
  });

  return <Show when={isLoading()}>
    <p>Redirecting...</p>
  </Show>
};
