// packages/playground/src/pages/Home/index.tsx
import React, { useCallback, useMemo, useContext } from 'react';

import LogtoClientContext from '@/LogtoClientContext';
import { baseUrl } from '@/consts/url';

import styles from './index.module.scss';

const Home = () => {
  const logtoClient = useContext(LogtoClientContext);

  if (!logtoClient) {
    throw new Error('no logto client found');
  }

  const isAuthed = useMemo(() => logtoClient.isAuthenticated(), [logtoClient]);
  const claims = isAuthed && logtoClient.getClaims();

  const signIn = useCallback(() => {
    void logtoClient.loginWithRedirect(`${baseUrl}/callback`);
  }, [logtoClient]);

  const signOut = useCallback(() => {
    logtoClient.logout(baseUrl);
  }, [logtoClient]);

  return (
    <div className={styles.wrapper}>
      <div className={styles.title}>Logto Playground</div>
      {!isAuthed && (
        <button type="button" onClick={signIn}>
          Sign In
        </button>
      )}
      {isAuthed && (
        <button type="button" onClick={signOut}>
          Sign Out
        </button>
      )}
      {claims && (
        <table className={styles.table}>
          <thead>
            <tr>
              <td>Name</td>
              <td>Value</td>
            </tr>
          </thead>
          <tbody>
            {Object.keys(claims).map((key) => (
              <tr key={key}>
                <td>{key}</td>
                <td>{claims[key as keyof typeof claims]}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
};

export default Home;

// packages/solid-sample/src/pages/Home.tsx
import { useLogto, type UserInfoResponse } from '@logto/solid';
import { createSignal, Show } from "solid-js";
import { baseUrl, redirectUrl } from '../consts';

const Home = () => {
  const {isAuthenticated, signIn, signOut, fetchUserInfo} = useLogto();
  const [user, setUser] = createSignal<UserInfoResponse>();

  (async () => {
    if (isAuthenticated()) {
      const userInfo = await fetchUserInfo();
      setUser(userInfo);
    }
  })();

  return (
    <div>
      <h3>Logto Solid sample</h3>
      <Show when={!isAuthenticated()}>
        <button
          type="button"
          onClick={() => {
            void signIn(redirectUrl);
          }}
        >
          Sign in
        </button>
        <button
          type="button"
          onClick={() => {
            void signIn(redirectUrl, 'signUp');
          }}
        >
          Sign up
        </button>
      </Show>
      <Show when={isAuthenticated()}>
        <button
          type="button"
          onClick={() => {
            void signOut(baseUrl);
          }}
        >
          Sign out
        </button>
      </Show>
      <Show when={isAuthenticated() && user()}>
        <table>
          <thead>
          <tr>
            <th>Name</th>
            <th>Value</th>
          </tr>
          </thead>
          <tbody>
          {Object.entries(user()).map(([key, value]) => (
            <tr>
              <td>{key}</td>
              <td>{typeof value === 'string' ? value : JSON.stringify(value)}</td>
            </tr>
          ))}
          </tbody>
        </table>
        <ul>
          <li>
            <a href="/protected">View protected resource</a>
          </li>
          <li>
            <a href="/protected/organizations">View organizations</a>
          </li>
        </ul>
      </Show>
    </div>
  );
};

export default Home;
