// packages/solid-sample/src/pages/Home.tsx
import { useLogto, type UserInfoResponse } from '@logto/solid';
import { createSignal, Show } from "solid-js";
import { baseUrl, redirectUrl } from '../consts';

const Home = () => {
  const {isAuthenticated, signIn, signOut, fetchUserInfo} = useLogto();
  const [user, setUser] = createSignal<UserInfoResponse>();

  (async () => {
    if (isAuthenticated()) {
      const userInfo = await fetchUserInfo();
      setUser(userInfo);
    }
  })();

  return (
    <div>
      <h3>Logto Solid sample</h3>
      <Show when={!isAuthenticated()}>
        <button
          type="button"
          onClick={() => {
            void signIn(redirectUrl);
          }}
        >
          Sign in
        </button>
        <button
          type="button"
          onClick={() => {
            void signIn(redirectUrl, 'signUp');
          }}
        >
          Sign up
        </button>
      </Show>
      <Show when={isAuthenticated()}>
        <button
          type="button"
          onClick={() => {
            void signOut(baseUrl);
          }}
        >
          Sign out
        </button>
      </Show>
      <Show when={isAuthenticated() && user()}>
        <table>
          <thead>
          <tr>
            <th>Name</th>
            <th>Value</th>
          </tr>
          </thead>
          <tbody>
          {Object.entries(user()).map(([key, value]) => (
            <tr>
              <td>{key}</td>
              <td>{typeof value === 'string' ? value : JSON.stringify(value)}</td>
            </tr>
          ))}
          </tbody>
        </table>
        <ul>
          <li>
            <a href="/protected">View protected resource</a>
          </li>
          <li>
            <a href="/protected/organizations">View organizations</a>
          </li>
        </ul>
      </Show>
    </div>
  );
};

export default Home;

// packages/react-playground/src/pages/Home/index.tsx
import { useLogto } from '@logto/react';
import React from 'react';

import { baseUrl } from '@/consts/url';

import styles from './index.module.scss';

const Home = () => {
  const { logout, loginWithRedirect, isAuthenticated, claims, isInitialized, isLoading } =
    useLogto();

  if (!isInitialized || isLoading) {
    return <div className={styles.wrapper}>fetching...</div>;
  }

  return (
    <div className={styles.wrapper}>
      <div className={styles.title}>Logto React Playground</div>
      {!isAuthenticated && (
        <button
          type="button"
          onClick={() => {
            void loginWithRedirect(`${baseUrl}/callback`);
          }}
        >
          Sign In
        </button>
      )}
      {isAuthenticated && (
        <button
          type="button"
          onClick={() => {
            logout(baseUrl);
          }}
        >
          Sign Out
        </button>
      )}
      {isAuthenticated && claims && (
        <table className={styles.table}>
          <thead>
            <tr>
              <td>Name</td>
              <td>Value</td>
            </tr>
          </thead>
          <tbody>
            {Object.keys(claims).map((key) => (
              <tr key={key}>
                <td>{key}</td>
                <td>{claims[key as keyof typeof claims]}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
};

export default Home;
