// packages/solid-sample/src/App.tsx
import { LogtoProvider, type LogtoConfig, UserScope } from "@logto/solid";
import { type RouteDefinition, Router } from "@solidjs/router";
import {lazy} from "solid-js";

import "./app.css";
import { appId, endpoint } from './consts';

const routes: RouteDefinition[] = [
  { path: '/', component: lazy(() => import("./pages/Home")) },
  { path: '/callback', component: lazy(() => import("./pages/Callback")) },
  { path: '/protected', component: lazy(() => import("./pages/ProtectedResource")) },
  { path: '/protected/organizations', component: lazy(() => import("./pages/Organizations")) },
];

export function App() {
  const config: LogtoConfig = {
    appId,
    endpoint,
    scopes: [
      UserScope.Email,
      UserScope.Phone,
      UserScope.CustomData,
      UserScope.Identities,
      UserScope.Organizations,
    ],
  };
  return (
    <LogtoProvider config={config}>
      <div class="flex flex-col min-h-screen">
        <Router>{routes}</Router>
      </div>
    </LogtoProvider>
  );
}

// packages/react-sample/src/App.tsx
import { LogtoProvider, type LogtoConfig, UserScope } from '@logto/react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';

import RequireAuth from './RequireAuth';
import { appId, endpoint } from './consts';
import Callback from './pages/Callback';
import Home from './pages/Home';
import ProtectedResource from './pages/ProtectedResource';

import './App.module.scss';

export const App = () => {
  const config: LogtoConfig = {
    appId,
    endpoint,
    scopes: [UserScope.Email, UserScope.Phone, UserScope.CustomData, UserScope.Identities],
  };

  return (
    <BrowserRouter>
      <LogtoProvider config={config}>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/callback" element={<Callback />} />
          <Route
            path="/protected-resource"
            element={
              <RequireAuth>
                <ProtectedResource />
              </RequireAuth>
            }
          />
        </Routes>
      </LogtoProvider>
    </BrowserRouter>
  );
};
